# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ballerina
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ballerina.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
breadcrumbs:
  root:
    hide: true  # show breadcrumbs on root/home page
    image: false # Show image or title text  
github_username:  ballerina-platform
git_repo: ballerina-dev-website
latest_version: Swan Lake 2201.0.2
#keep_files: ['0.990','0.991',"1.1"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: ["downloads/RELEASE_NOTE.md","vendor","0.991/","v1-2","v1-1","v1-0","v0-991","v-0.990","0.990","1.0"]
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
dist_server: https://dist-dev.ballerina.io
plugin_vscode_repo: https://github.com/ballerina-platform/plugin-vscode
algolia:
  # application_id: VEFFNV19B3
  # index_name: jekyll wso2-ballerina-docs 
  # search_only_api_key: 737b0009164fdf533343caa89c328667
  application_id: 1UGB2K5V0K
  index_name: jekyll wso2_bbe_dev_sameeral 
  search_only_api_key: fbb148c3fb14152176aec9976c0f425d
defaults:
  -
    scope:
      path:            "1.1"
    values:
      sitemap:         false
  -
    scope:
      path:            "1.0"
    values:
      sitemap:         false
  -
    scope:
      path:            "1.2"
    values:
      sitemap:         false
  -
    scope:
      path:            "_posts"
    values:
      sitemap:         false
