POST http://localhost:8080/api/v1
content-type: application/json
X-REQUEST-TYPE: GraphQL

mutation ($orgID: String!, $projRequest: ProjectRequest!) {
  createProject(organizationID: $orgID, projectRequest: $projRequest) {
    projectName,
    customerName,
    description,
    tasks {
      taskID,
      description
    }
  }
}

{
  "orgID": "10234696",
  "projRequest": {
    "projectName": "Epidata Fuse",
    "customerName": "MCD Corp",
    "description": "A generic faramework for fusion and integration of spatio-temporal data for disease surveillance"
  }
}
