POST http://localhost:8080/api/v1/survey/0034
userId: 00041

{
    "Q1": 4,
    "Q2": 8,
    "Q3": 7,
    "Q4": 8
}

###

POST http://localhost:8080/api/v1/survey/0034
userId: 00041


{
    "Q5": 6,
    "Q6": 6,
    "Q7": 7,
    "Q8": 9
}

###

POST http://localhost:8080/api/v1/survey/0034
userId: 00041

{
    "Q9": 5,
    "Q10": 6,
    "Q11": 7,
    "Q12": 9
}
