# This is the config of the spell checker GitHub Action (i.e., https://github.com/marketplace/actions/check-spelling).

on: [pull_request]
name: Check spelling
jobs:
  spellChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check spelling
      - uses: check-spelling/check-spelling@0.0.16-alpha