name: Sync artifacts from dev to prod

on:
  push:
    branches:
      - prod-sync
    paths:
      - '_data/latest/**'

jobs:
  prod-artifact-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq for json
      run: sudo apt-get install jq
      
    - name: Sync artifacts from dev to prod
      shell: bash
      env:
        s3_acc_id: ${{ secrets.S3_ID }}
        s3_acc_key: ${{ secrets.S3_KEY }}
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -q awscliv2.zip
        sudo ./aws/install
        aws configure set aws_access_key_id $s3_acc_id
        aws configure set aws_secret_access_key $s3_acc_key

        version="`jq -r '.version' _data/latest/metadata.json`"
        echo "extracted release version: $version"

        aws s3 cp s3://dist-dev.ballerina.io/downloads/$version/ s3://dist.ballerina.io/downloads/$version/ --recursive

