name: Push changes of prod-sync to prod-site

on:
  push:
    branches:
      - prod-sync

jobs:
  prod-sync:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
    steps:   
    - name: Clone production b.io
      run: git clone https://ballerina-bot:$GITHUB_TOKEN@github.com/ballerina-platform/ballerina-platform.github.io.git

    - name: Sync production repo with prod-sync branch
      run: |
        cd ballerina-platform.github.io
        git pull origin master

        git config --global user.email "ballerina-bot@ballerina.org"
        git config --global user.name "ballerina-bot"

        git remote add dev https://github.com/ballerina-platform/ballerina-dev-website.git
        git pull dev prod-sync -X theirs --no-edit --no-rebase
        
    - name: Push changes to prod website
      shell: bash
      run: |
        cd ballerina-platform.github.io
        curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
        bin/hub push
      env:
        GITHUB_TOKEN: ${{ secrets.WEBSITE_TOKEN }}
